### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by vovanec** [k-yle/Pebble-Wikipedia#1]
First of all, very cool app, thanks! Can you please address a couple of things:
- Hide/make inactive dictation button on aplite. It's not supposed to work anyway, having it clickable on aplite is just confusing.
- Make vibration optional/configurable. I think it may be annoying for some people, I'd personally disabled it.

**Comment by k-yle** [comment]
I've just done both, as well as chalk support. Thanks for the suggestions!
